const books = [
    {
        "_id":1,
        "name":"Sherlock Holmes",
        "image":"/images/Sherlock.jpg",
        "description":"The Return of Sherlock Holmes is a 1905 collection of 13 Sherlock Holmes stories, originally published in 1903–1904, by Arthur Conan Doyle. The stories were published in the Strand Magazine in Britain and Collier's in the United States.",
        "author":"Aurther Conan Doyle",
        "genre":"Fiction",
        "price":10,
        "countInStock":5,
        "rating":4.5,
        "numReviews":12
    },
    {
        "_id":2,
        "name":"Game of Thrones",
        "image":"/images/got.jpg",
        "description":"Set in the fictional continents of Westeros and Essos, the narrative revolves around the power struggles among noble families vying for the Iron Throne, the seat of power in the Seven Kingdoms of Westeros. The story is rich with political intrigue, betrayal, and epic battles, as well as a deep exploration of themes such as loyalty, honor, and the consequences of power.",
        "author":"George R.R Martin",
        "genre":"Fiction",
        "price":12,
        "countInStock":10,
        "rating":4.8,
        "numReviews":20,
    },
    {
        "_id":3,
        "name":"Twilight",
        "image":"/images/Twilight.jpg",
        "description":"A beautifully written book by Stephanie Meyer. This book will take you on an adventure like no other, the epic romance of a 110 year old vampire frozen in the body of a 17 year old, an 18 year old human named Isabella Swan. Join Edward Cullen and Bella Swan on this action packed romance.",
        "author":"Stephyen Meyer",
        "genre":"Fiction",
        "price":9,
        "countInStock":0,
        "rating":4.4,
        "numReviews":15,
    },
    {
        "_id":4,
        "name":"Robinson Crusoe",
        "image":"/images/RobinsonCrusoe.jpg",
        "description":"The Life and Strange Surprising Adventures of Robinson Crusoe, Of York, Mariner: Who lived Eight and Twenty Years, all alone in an un-inhabited Island on the Coast of America, near the Mouth of the Great River of Oroonoque; Having been cast on Shore by Shipwreck, wherein all the Men perished but himself. With An Account how he was at last as strangely deliver'd by Pyrates.",
        "author":"Daniel Defoe",
        "genre":"Fiction",
        "price":15,
        "countInStock":3,
        "rating":4.9,
        "numReviews":20,
    },
    {
        "_id":5,
        "name":"The Subtle Art of Not Giving a F*ck",
        "image":"/images/TheSubtleArt.jpg",
        "description":"In this book, blogger and former internet entrepreneur Mark Manson explains in simple, no expletives barred terms how to achieve happiness by caring more about fewer things and not caring at all about more.",
        "author":"Mark Manson",
        "genre":"Non-Fiction",
        "price":18,
        "countInStock":6,
        "rating":4.7,
        "numReviews":17,
    },
    {
        "_id":6,
        "name":"The 7 Habits of Highly Effective People",
        "image":"/images/7Habits.jpg",
        "description":"It’s a book that makes you face yourself and think about what can you do to change your results.",
        "author":"Stephen R.Covey",
        "genre":"Non-Fiction",
        "price":17,
        "countInStock":8,
        "rating":3.6,
        "numReviews":18,
    },
    {
        "_id":7,
        "name":"How to Win Friends and Influence People",
        "image":"/images/WinFriends.jpg",
        "description":"Available for the first time ever in trade paperback, Dale Carnegie's enduring classic, the inspirational personal development guide that shows how to achieve lifelong success. One of the top-selling books of all time, has sold more than 15 million copies in all its editions.",
        "genre":"Non-Fiction",
        "price":13,
        "countInStock":3,
        "rating":4.2,
        "numReviews":16,
    },
    {
        "_id":8,
        "name":"Sapiens",
        "image":"/images/Sapiens.jpg",
        "description":"From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be “human.”",
        "genre":"Non-Fiction",
        "price":12,
        "countInStock":9,
        "rating":4.2,
        "numReviews":20,
    }

]
export default books;